isActive frontend
MathForABetterWorld/MathForABetterWorld pull request #169
Opened 2023-08-03 18:00 UTC by jstelnik

**QUESTION**: should we change the view users page to include a dataframe similar to the categories, distributors page and also be able to add, edit, delete users there

2023-08-03 18:01 UTC, jstelnik commented
QUESTION: should we change the view users page to include a dataframe similar to the categories, distributors page and also be able to add, edit, delete users there

2023-08-03 18:09 UTC, ChrisWilhelm commented
@jstelnik no, not all employees have this ability. Just admins

2023-08-03 18:11 UTC, ChrisWilhelm requested changes

2023-08-03 18:11 UTC, ChrisWilhelm commented on client-employee/pages/14_Create_New_User.py
> +        isActive = True
the user connector does not get this field

2023-08-03 18:19 UTC, ChrisWilhelm requested changes

2023-08-03 18:19 UTC, ChrisWilhelm commented on client-employee/routeConnectors/userConnector.py
> +      "isActive": True
isActive is also not a field on the post request on the backend.

2023-08-04 19:00 UTC, jstelnik commented
> @jstelnik no, not all employees have this ability. Just admins

@ChrisWilhelm so if a user is logged in and they are an admin, they have the ability to change a user from active to inactive?

2024-03-07 04:17 UTC, closed without merging